In [1]:
import numpy as np
Y = np.array([[5, 1, 4, 5, 1], [0, 5, 2, 1, 4], [1, 4, 1, 1, 2],\
              [4, 1, 5, 5, 4], [5, 3, 4, 5, 4], [1, 5, 1, 1, 1], \
              [5, 1, 0, 5, 4]])

R = np.array([[1,1,1,1,1],[0,1,1,1,1],[1,1,1,1,1],
              [1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],
              [1,1,0,1,1]])
print(Y)
print R

[[5 1 4 5 1]
 [0 5 2 1 4]
 [1 4 1 1 2]
 [4 1 5 5 4]
 [5 3 4 5 4]
 [1 5 1 1 1]
 [5 1 0 5 4]]
[[1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 1 1]]


In [2]:
U = np.random.random((7,2))
print U.shape

(7, 2)


In [3]:
V = np.random.random((5,2))
print V

[[ 0.82397402  0.60852427]
 [ 0.50909601  0.49249144]
 [ 0.25436493  0.33653035]
 [ 0.98762177  0.18856459]
 [ 0.85740707  0.28557033]]


In [4]:
V_t = np.transpose(V)
print V_t.shape
print V.shape

(2, 5)
(5, 2)


In [12]:
U_new = U + 2* (1/33)*(0.01)* np.dot((R*(Y-(np.dot(U, V_t)))), V) 
V_new = V + 2* float(1/33)*(0.01)* np.dot(np.transpose(R*(Y-(np.dot(U, V_t)))), U) 

print U_new
print V_new

print U_new.shape
print V_new.shape


[[ 0.39417389  0.06546471]
 [ 0.97543933  0.69108896]
 [ 0.76484684  0.69724213]
 [ 0.77081656  0.02274227]
 [ 0.39221205  0.09461844]
 [ 0.10174674  0.27917272]
 [ 0.22890381  0.78488505]]
[[ 0.82397402  0.60852427]
 [ 0.50909601  0.49249144]
 [ 0.25436493  0.33653035]
 [ 0.98762177  0.18856459]
 [ 0.85740707  0.28557033]]
(7, 2)
(5, 2)


In [9]:
error = (1/33)*float(Y - np.dot(U, np.transpose(V)))
print error

TypeError: only length-1 arrays can be converted to Python scalars